import { motion } from "framer-motion"
import { Line, Bar, Pie, Scatter } from "react-chartjs-2"

const MultiChartGrid = ({ rows, colsMeta, autoGenerated = false, fileName = "", recordCount = 0 }) => {
  if (!rows || !colsMeta || rows.length === 0) return null

  const numberCols = colsMeta.filter(c => c.type === "number")
  const categoryCols = colsMeta.filter(c => c.type === "categorical")
  const dateCols = colsMeta.filter(c => c.type === "date")

  const chartConfigs = []

  // Generate multiple chart combinations
  if (numberCols.length >= 2) {
    // Scatter: Number vs Number
    chartConfigs.push({
      type: "scatter",
      x: numberCols[0].name,
      y: numberCols[1].name,
      title: `${numberCols[1].name} vs ${numberCols[0].name}`
    })
  }

  if (dateCols.length > 0 && numberCols.length > 0) {
    // Line chart: Date vs Number
    chartConfigs.push({
      type: "line",
      x: dateCols[0].name,
      y: numberCols[0].name,
      title: `${numberCols[0].name} over ${dateCols[0].name}`
    })
  }

  if (categoryCols.length > 0 && numberCols.length > 0) {
    // Bar chart: Category vs Number
    chartConfigs.push({
      type: "bar",
      x: categoryCols[0].name,
      y: numberCols[0].name,
      title: `${numberCols[0].name} by ${categoryCols[0].name}`
    })
  }

  if (categoryCols.length > 0 && numberCols.length > 0) {
    // Pie chart
    chartConfigs.push({
      type: "pie",
      x: categoryCols[0].name,
      y: numberCols[0].name,
      title: `Distribution of ${numberCols[0].name}`
    })
  }

  if (numberCols.length > 1) {
    // Line chart: Number vs Number
    chartConfigs.push({
      type: "line",
      x: numberCols[0].name,
      y: numberCols[1].name,
      title: `${numberCols[1].name} over ${numberCols[0].name}`
    })
  }

  const buildChartData = (xcol, ycol, chartType) => {
    const xMeta = colsMeta.find((c) => c.name === xcol)
    const yMeta = colsMeta.find((c) => c.name === ycol)

    const bgColors = ["#FF6B6B", "#4ECDC4", "#45B7D1", "#FFA07A", "#98D8C8", "#F7DC6F"]

    if (chartType === "pie") {
      if (xMeta && xMeta.type === "categorical" && yMeta && yMeta.type === "number") {
        const grouped = {}
        rows.forEach((r) => {
          const k = String(r[xcol])
          const v = Number(r[ycol]) || 0
          grouped[k] = (grouped[k] || 0) + v
        })
        return {
          labels: Object.keys(grouped),
          datasets: [{
            data: Object.values(grouped),
            backgroundColor: bgColors,
            borderColor: "#fff",
            borderWidth: 2
          }]
        }
      }
    }

    if (chartType === "scatter") {
      const data = rows.map((r) => {
        const x = Number(r[xcol])
        const y = Number(r[ycol])
        if (isNaN(x) || isNaN(y)) return null
        return { x, y }
      }).filter(Boolean)
      return {
        datasets: [{
          label: `${ycol} vs ${xcol}`,
          data,
          backgroundColor: "rgba(99, 102, 241, 0.6)",
          borderColor: "rgb(99, 102, 241)",
          borderWidth: 2
        }]
      }
    }

    if (chartType === "line") {
      let points = rows.map((r) => ({ x: r[xcol], y: Number(r[ycol]) }))
      if (xMeta && xMeta.type === "date") {
        points = points.map((p) => ({ x: new Date(p.x).getTime(), y: p.y })).filter((p) => !isNaN(p.x))
        return {
          datasets: [{
            label: ycol,
            data: points.map((p) => ({ x: p.x, y: p.y })),
            fill: true,
            backgroundColor: "rgba(99, 102, 241, 0.1)",
            borderColor: "rgb(99, 102, 241)",
            borderWidth: 3,
            tension: 0.4,
            pointRadius: 4,
            pointBackgroundColor: "rgb(99, 102, 241)"
          }]
        }
      }

      const labels = rows.map((r) => String(r[xcol]))
      const data = rows.map((r) => Number(r[ycol]) || 0)
      return {
        labels,
        datasets: [{
          label: ycol,
          data,
          fill: true,
          backgroundColor: "rgba(99, 102, 241, 0.1)",
          borderColor: "rgb(99, 102, 241)",
          borderWidth: 3,
          tension: 0.4,
          pointRadius: 4,
          pointBackgroundColor: "rgb(99, 102, 241)"
        }]
      }
    }

    if (chartType === "bar") {
      if (xMeta && xMeta.type === "categorical" && yMeta && yMeta.type === "number") {
        const grouped = {}
        rows.forEach((r) => {
          const k = String(r[xcol])
          const v = Number(r[ycol]) || 0
          grouped[k] = (grouped[k] || 0) + v
        })
        return {
          labels: Object.keys(grouped),
          datasets: [{
            label: ycol,
            data: Object.values(grouped),
            backgroundColor: "rgba(99, 102, 241, 0.7)",
            borderColor: "rgb(99, 102, 241)",
            borderWidth: 2,
            borderRadius: 6
          }]
        }
      }

      const labels = rows.map((r) => String(r[xcol] ?? ""))
      const data = rows.map((r) => Number(r[ycol]) || 0)
      return {
        labels,
        datasets: [{
          label: ycol,
          data,
          backgroundColor: "rgba(99, 102, 241, 0.7)",
          borderColor: "rgb(99, 102, 241)",
          borderWidth: 2,
          borderRadius: 6
        }]
      }
    }
    return null
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="mt-8"
    >
      <div className="mb-6">
        <h3 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">
          {fileName || (autoGenerated ? "Auto-Generated Charts" : "Multi-Chart Analysis")}
        </h3>
        <p className="text-sm text-gray-600 dark:text-gray-400">
          {recordCount > 0 ? `${recordCount} records loaded` : `Showing ${chartConfigs.length} different data visualizations`}
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {chartConfigs.map((config, idx) => {
          const data = buildChartData(config.x, config.y, config.type)
          if (!data) return null

          return (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: idx * 0.1 }}
              className="bg-white dark:bg-gray-800 rounded-xl shadow-lg border border-gray-200 dark:border-gray-700 p-6"
            >
              <h4 className="text-lg font-semibold text-gray-900 dark:text-white mb-4 truncate">
                {config.title}
              </h4>
              <div style={{ height: 300, position: "relative", minHeight: 300 }}>
                {config.type === "line" && (
                  <Line
                    options={{
                      responsive: true,
                      maintainAspectRatio: false,
                      plugins: { legend: { display: true } },
                      scales: {
                        x: { type: (colsMeta.find(c => c.name === config.x)?.type === "date") ? "time" : "category" }
                      }
                    }}
                    data={data}
                  />
                )}
                {config.type === "bar" && (
                  <Bar
                    options={{
                      responsive: true,
                      maintainAspectRatio: false,
                      indexAxis: "x"
                    }}
                    data={data}
                  />
                )}
                {config.type === "pie" && (
                  <Pie
                    options={{
                      responsive: true,
                      maintainAspectRatio: false,
                      plugins: { legend: { position: "bottom" } }
                    }}
                    data={data}
                  />
                )}
                {config.type === "scatter" && (
                  <Scatter
                    options={{
                      responsive: true,
                      maintainAspectRatio: false,
                      scales: { y: { beginAtZero: true } }
                    }}
                    data={data}
                  />
                )}
              </div>
            </motion.div>
          )
        })}
      </div>
    </motion.div>
  )
}

export default MultiChartGrid
